apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rds-backup-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rds-backup
            image: rds-backup:latest
            env:
            - name: AWS_REGION
              value: us-west-2
