apiVersion: v1
kind: ServiceAccount
metadata:
  name: rds-automation-cross-account
  namespace: jfrog-saas-rds-automation
imagePullSecrets:
  - name: repo21edgesaliasingress-jfrog-io-pull-secret

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rds-automation-main
  namespace: jfrog-saas-rds-automation
imagePullSecrets:
  - name: repo21edgesaliasingress-jfrog-io-pull-secret