apiVersion: batch/v1
kind: CronJob
metadata:
  name: main-backup-afs1
  namespace: jfrog-saas-rds-automation
  labels:
    customerName: devops-infra
    owner: devops
    subscriptionType: thirdparty
    purpose: infra
    environment: production 
spec:
  concurrencyPolicy: Forbid
  schedule: "0 10,22 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            application: main-backup          
            region: af-south-1
            customerName: devops-infra
            owner: devops
            subscriptionType: thirdparty
            purpose: infra
            environment: production                   
          annotations:
            logging_index: devops-infra      
        spec:        
          serviceAccountName: rds-automation-main
          restartPolicy: Never
          imagePullSecrets:
            - name: repo21edgesaliasingress-jfrog-io-pull-secret
          containers:
            - name: main-backup-afs1
              image: repo21edgesaliasingress.jfrog.io/enterprise-docker/jfrog/devops/rds-automation:v1.10
              imagePullPolicy: IfNotPresent
              command: ["python", "app/rds_backup.py"]
              env:
                - name: APPLICATION
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['application']
                - name: ENVIRONMENT 
                  value: "Production"
                - name: SOURCE_ACCOUNT_ID
                  value: "152153062141"
                - name: DST_ACCOUNT_ID
                  value: "767397968472"
                - name: REGION
                  value: "af-south-1"
                - name: "WORKLOAD_TYPE"
                  value: "main"
                - name: SLACK_WEBHOOK_URL
                  value: "https://hooks.slack.com/services/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"
              resources:
                requests:
                  memory: "300Mi"
                  cpu: "50m"
                limits:
                  memory: "300Mi"
                  cpu: "50m"
              securityContext:
                allowPrivilegeEscalation: false 
                
