name: 'Build and Deploy Pulumi Cloud Function'

on:
  push:
    branches:
      - 'main'

jobs:
  preview:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11        
      - name: Authticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      - name: Install Dependencies
        working-directory: pulumi-cloud-function
        run: pip install -r requirements.txt
      - uses: pulumi/actions@v6
        with:
          command: preview --diff
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      

